### ISSUE TITLE
Cant add spell

### ISSUE THREAD

**Issue by Kj7CR7** [NotNite/BetterInBlue#3]
Since the last update, I am no longer able to add magic.
All other functions are working fine.

Reinstalling the plugin has not solved the problem.
please look at the picture.

The same report has been issued in Discord.
https://discord.com/channels/581875019861328007/684745859497590843/1179722855525646386
https://discord.com/channels/581875019861328007/684745859497590843/1184068150615097394

![better in blue not working](https://github.com/NotNite/BetterInBlue/assets/149914941/21cb1f9d-2178-4d87-ac19-65682bcc766f)

**Comment by Writingnon** [comment]
Yeah, I got this problem as well.

**Comment by NotNite** [comment]
Fixed - will be updated soon. Sorry!
